apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellok8s
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 10
  selector:
    matchLabels:
      app: hellok8s
  template:
    metadata:
      labels:
        app: hellok8s
    spec:
      containers:
      - image: hellok8s:v4
        name: hellok8s-container
        ports:
        - containerPort: 4567
        readinessProbe:
          periodSeconds: 1
          successThreshold: 5
          httpGet:
            path: /
            port: 4567
        livenessProbe:
          exec: 
            command:
            - /bin/sh
            - -c
            - /app/check_health.sh